
name: chicagofed2016

channels:
 - conda-forge

dependencies:
  - python=3.5
  - anaconda
  - matplotlib
  - pandas=0.18.1
  - ruamel.yaml=0.11.11
  - xlrd
  - numba
  - pandas-datareader
  - numpy
  - sympy
  - pyyaml
  - pip:
    - quantecon
    - interpolation
    - dolo

